// GENERATED by scripts/gen-barrels.mjs — do not edit by hand.
//
// The labelled cylinder of each product, measured from public/models/parts/*.glb.
// Axis is +Z; radius is the radial extent in X/Y; bands are the z-ranges where a
// black collar sits proud of the barrel and no label may be printed.

export interface Barrel {
  /** The body material, which decides whether the mark is white or dark. */
  material: string
  radius: number
  z0: number
  z1: number
  /** Black collars crossing the barrel, as [z0, z1] pairs, ordered along the axis. */
  bands: [number, number][]
  /** Full model extent along the axis, brackets excluded. Its height when stood up. */
  length: number
  /** Widest radius of the model, brackets excluded. Its half-width when stood up. */
  modelRadius: number
  /**
   * Extent across the axis in Y as [min, max], brackets excluded, and NOT assumed
   * symmetric. Bodies of revolution give [-radius, +radius]; the PX 5 carries its
   * handle on one side only. This is the unit's height when it is laid down.
   */
  crossY: [number, number]
}

export const BARRELS: Record<string, Barrel> = {
  px1e: { material: 'GF_RedAnodized', radius: 0.016, z0: 0, z1: 0.204, bands: [[0,0.0136]], length: 0.34, modelRadius: 0.01856, crossY: [-0.01856,0.01856] },
  px1m: { material: 'GF_RedAnodized', radius: 0.0175, z0: 0, z1: 0.124, bands: [[0,0.01],[0,0.026]], length: 0.2, modelRadius: 0.08838, crossY: [-0.01837,0.01837] },
  px5: { material: 'GF_RedPolymer', radius: 0.0755, z0: 0.00004, z1: 0.2, bands: [], length: 0.29996, modelRadius: 0.15609, crossY: [-0.08,0.15609] },
  sx100: { material: 'GF_RedAnodized', radius: 0.016, z0: 0, z1: 0.19976, bands: [], length: 0.227, modelRadius: 0.016, crossY: [-0.016,0.016] },
  sx1500: { material: 'GF_Stainless', radius: 0.09, z0: 0, z1: 0.1591, bands: [[0.0258,0.03655],[0.1204,0.13115]], length: 0.215, modelRadius: 0.0936, crossY: [-0.0936,0.0936] },
  sx25: { material: 'GF_RedAnodized', radius: 0.016, z0: 0, z1: 0.11616, bands: [], length: 0.132, modelRadius: 0.016, crossY: [-0.016,0.016] },
  sx300: { material: 'GF_Stainless', radius: 0.047, z0: 0, z1: 0.13542, bands: [[0.02196,0.03111],[0.10248,0.11163]], length: 0.183, modelRadius: 0.04888, crossY: [-0.04888,0.04888] },
  sx50: { material: 'GF_RedAnodized', radius: 0.016, z0: 0, z1: 0.14256, bands: [], length: 0.162, modelRadius: 0.016, crossY: [-0.016,0.016] },
  sx500: { material: 'GF_Stainless', radius: 0.047, z0: 0, z1: 0.1591, bands: [[0.0258,0.03655],[0.1204,0.13115]], length: 0.215, modelRadius: 0.04888, crossY: [-0.04888,0.04888] },
  sx5_10: { material: 'GF_RedAnodized', radius: 0.0095, z0: 0, z1: 0.1035, bands: [], length: 0.115, modelRadius: 0.0095, crossY: [-0.0095,0.0095] },
  sx750: { material: 'GF_Stainless', radius: 0.047, z0: 0, z1: 0.1813, bands: [[0.0294,0.04165],[0.1372,0.14945]], length: 0.245, modelRadius: 0.04888, crossY: [-0.04888,0.04888] },
}
