// GENERATED by scripts/build-decal-atlas.mjs — do not edit by hand.
//
// Cell rectangles in the decal atlas, in UV space with v=0 at the bottom, plus
// each cell's aspect ratio so geometry can be built without distorting the art.
// Written from the same layout that positioned the pixels, so these cannot drift
// from public/textures/decals.png.

export interface AtlasCell {
  u0: number
  v0: number
  u1: number
  v1: number
  /** width / height of the cell, for sizing panels without stretching type. */
  aspect: number
}

export const DECAL_ATLAS: {
  wordmark: AtlasCell
  arrow: AtlasCell
  numbers: Record<string, AtlasCell | undefined>
} = {
  wordmark: {"u0":0.007813,"v0":0.787109,"u1":0.992188,"v1":0.992188,"aspect":4.8},
  arrow: {"u0":0.007813,"v0":0.154297,"u1":0.183594,"v1":0.271484,"aspect":1.5},
  numbers: {
    "PX1M": {"u0":0.007813,"v0":0.654297,"u1":0.330078,"v1":0.771484,"aspect":2.75},
    "PX1E": {"u0":0.337891,"v0":0.654297,"u1":0.660156,"v1":0.771484,"aspect":2.75},
    "PX 5": {"u0":0.667969,"v0":0.654297,"u1":0.990234,"v1":0.771484,"aspect":2.75},
    "SX 5/10": {"u0":0.007813,"v0":0.529297,"u1":0.330078,"v1":0.646484,"aspect":2.75},
    "SX 25": {"u0":0.337891,"v0":0.529297,"u1":0.660156,"v1":0.646484,"aspect":2.75},
    "SX 50": {"u0":0.667969,"v0":0.529297,"u1":0.990234,"v1":0.646484,"aspect":2.75},
    "SX 100": {"u0":0.007813,"v0":0.404297,"u1":0.330078,"v1":0.521484,"aspect":2.75},
    "SX 300": {"u0":0.337891,"v0":0.404297,"u1":0.660156,"v1":0.521484,"aspect":2.75},
    "SX 500": {"u0":0.667969,"v0":0.404297,"u1":0.990234,"v1":0.521484,"aspect":2.75},
    "SX 750": {"u0":0.007813,"v0":0.279297,"u1":0.330078,"v1":0.396484,"aspect":2.75},
    "SX 1500": {"u0":0.337891,"v0":0.279297,"u1":0.660156,"v1":0.396484,"aspect":2.75},
  },
}

/** Model number as printed, by product id. Order matches assets/products.json. */
export const MODEL_NUMBER: Record<string, string> = {
  px1m: 'PX1M',
  px1e: 'PX1E',
  px5: 'PX 5',
  sx5_10: 'SX 5/10',
  sx25: 'SX 25',
  sx50: 'SX 50',
  sx100: 'SX 100',
  sx300: 'SX 300',
  sx500: 'SX 500',
  sx750: 'SX 750',
  sx1500: 'SX 1500',
}
