'use client'

import { createContext, useContext, useMemo } from 'react'
import { useTexture } from '@react-three/drei'
import * as THREE from 'three'

import { BARRELS } from '@/lib/barrels'
import { DECAL_ATLAS, MODEL_NUMBER, type AtlasCell } from '@/lib/decalAtlas'

/**
 * The printed markings on a product: GENEFIRE wordmark, model number, discharge
 * arrow.
 *
 * WHY GEOMETRY AND NOT A UV BAND. The source .glb files carry POSITION only — no
 * TEXCOORD_0 and no NORMAL — so there is nothing to map a band onto. DecalGeometry
 * would work but wants a projector set up per marking per product, and it
 * retriangulates the target mesh, which the exploded view in §05 then has to
 * separate. Curved panels floating just off the barrel are the cheapest of the
 * three and the only one that needs nothing from the source mesh.
 *
 * All markings for one product merge into ONE geometry sharing ONE material, so a
 * fully decalled product costs a single extra draw call. Eleven on screen in the
 * hero is eleven calls, which is what keeps this inside the 60-call budget.
 *
 * Sizing is a compromise between two rules that disagree, and it has to be:
 *
 *   - Constant physical type size is what a real label has, but a 9.5 mm SX 5/10
 *     bar and an 80 mm PX 5 body differ by a factor of eight in circumference, so
 *     one physical size wraps 82° of the thin one and 18° of the fat one.
 *   - Constant angular size reads consistently, but on the PX 5 it demands a mark
 *     386 mm long on a 216 mm barrel.
 *
 * So each marking takes the SMALLER of a fraction of the clear barrel run and a
 * fraction of the circumference. Nothing is ever stretched: length always follows
 * from the atlas cell's own aspect ratio.
 *
 * Four copies at 90° around the barrel. A printed label is legible across a window
 * of maybe 60°, and in the hero eleven products sit at eleven different angles —
 * with one copy most of them would show a blank cylinder.
 */

/** Radial clearance, as a fraction of barrel radius. Enough to beat z-fighting. */
const PROUD = 1.006

/** No marking may take more than this fraction of the clear run along the axis. */
const MAX_AXIAL = 0.5

/** Nor more than this fraction of the circumference, measured across the type. */
const MAX_ARC = 0.17

/** Segments around the arc. A label spanning 80° needs curvature; 12 is plenty. */
const SEGMENTS = 12

/**
 * How the product this marking belongs to is presented.
 *
 * 'upright' is every product everywhere on the site: stood on its base, turning
 * about the axis it actually has, so every copy of the label comes round reading
 * the same way and none needs its artwork flipped.
 *
 * 'lying' is the hero PX 5 alone — see lib/heroStage.ts. A cylinder laid on its
 * side and turned about the VERTICAL axis is the case the flip exists for. The
 * label runs along the barrel; at one end of the turn the barrel points screen-
 * right and the label reads correctly, and half a revolution later the same barrel
 * points screen-left and every copy facing the camera reads BACKWARDS. It is not a
 * subtle artefact: the opening frame of the site showed a mirrored GENEFIRE
 * wordmark for half of every rotation.
 *
 * Supplied by CONTEXT rather than by a prop because the product components are
 * generated by scripts/gen-product-components.mjs, which injects
 * `<ProductDecals id="…" />` with no way to pass anything through. Context lets the
 * hero re-pose the same generated component without the generator knowing.
 */
export type DecalPose = 'upright' | 'lying'

export const DecalPoseContext = createContext<DecalPose>('upright')

interface Marking {
  cell: AtlasCell
  /** Centre of the marking along the axis, in metres. */
  z: number
  /** Length along the axis, in metres. */
  length: number
  /** Centre angle, radians. */
  theta: number
  /** Turn the artwork through 180°, for the copy that comes round reversed. */
  flip?: boolean
}

/**
 * Push one curved panel into the vertex arrays.
 *
 * The atlas cell's WIDTH runs along +Z and its HEIGHT runs around the barrel, so
 * the type reads along the length of the cylinder — which is how it is printed on
 * the real units in assets/photos/.
 */
function pushPanel(
  positions: number[],
  normals: number[],
  uvs: number[],
  radius: number,
  { cell, z, length, theta, flip }: Marking,
) {
  /*
    `flip` ROTATES the artwork 180°. It does not mirror it, and the difference is
    the whole point.

    On the copy this applies to, BOTH of the panel's axes come round reversed: u
    runs with +Z, which points screen-left once the unit has turned end for end, and
    v runs with the wrap angle, which at that side of the barrel descends rather
    than climbs. Reversing u alone cancels one of the two and leaves the other — and
    a label with its letters in the right order and every glyph upside down is not
    an improvement on a mirrored one. It is what the first attempt at this shipped:
    "PX 5" rendered as "bX 2".

    Two labels on one cylinder, each reading correctly from its own side, ARE
    printed at 180° to each other. This is what that looks like in UV.
  */
  const u0 = flip ? cell.u1 : cell.u0
  const u1 = flip ? cell.u0 : cell.u1
  const cv0 = flip ? cell.v1 : cell.v0
  const cv1 = flip ? cell.v0 : cell.v1
  const arc = length / cell.aspect
  const phi = arc / radius
  const r = radius * PROUD
  const z0 = z - length / 2
  const z1 = z + length / 2

  for (let i = 0; i < SEGMENTS; i++) {
    const a0 = theta + (i / SEGMENTS - 0.5) * phi
    const a1 = theta + ((i + 1) / SEGMENTS - 0.5) * phi
    const v0 = cv0 + (i / SEGMENTS) * (cv1 - cv0)
    const v1 = cv0 + ((i + 1) / SEGMENTS) * (cv1 - cv0)

    const corner = (a: number, zz: number, u: number, v: number) => {
      const sx = Math.sin(a)
      const sy = Math.cos(a)
      positions.push(sx * r, sy * r, zz)
      normals.push(sx, sy, 0)
      uvs.push(u, v)
    }

    // Two triangles, wound so the FRONT face points away from the axis.
    //
    // The winding is what decides culling, not the normal attribute — supplying
    // an outward normal on an inward-wound triangle gets you a correctly lit
    // surface that is then thrown away before it is drawn. For p(a,z) =
    // (r·sin a, r·cos a, z), ∂p/∂a × ∂p/∂z points along +X at a = -π/2 where the
    // outward radial is -X, so the naive order is inside-out and every panel
    // vanishes under FrontSide.
    corner(a0, z0, u0, v0)
    corner(a1, z1, u1, v1)
    corner(a1, z0, u0, v1)

    corner(a0, z0, u0, v0)
    corner(a0, z1, u1, v0)
    corner(a1, z1, u1, v1)
  }
}

/**
 * Lay the markings out along the barrel.
 *
 * The black collars are obstacles: on the real units the printed label sits
 * between them and never across one, so the longest gap between collars — or the
 * whole barrel when there are none — is the run everything has to fit in.
 */
function layout(id: string, pose: DecalPose): Marking[] | null {
  const barrel = BARRELS[id]
  const number = MODEL_NUMBER[id]
  if (!barrel || !number) return null

  const numberCell = DECAL_ATLAS.numbers[number]
  if (!numberCell) return null

  // Longest clear run between collars.
  const edges = [barrel.z0, ...barrel.bands.flat(), barrel.z1]
  let best: [number, number] = [barrel.z0, barrel.z1]
  for (let i = 0; i < edges.length - 1; i += 2) {
    const a = edges[i]
    const b = edges[i + 1]
    if (b - a > best[1] - best[0] || i === 0) {
      if (b - a > best[1] - best[0]) best = [a, b]
    }
  }
  if (barrel.bands.length === 0) best = [barrel.z0, barrel.z1]

  const span = best[1] - best[0]
  if (span <= 0) return null

  const circumference = 2 * Math.PI * barrel.radius

  /** Length that respects both the axial run and the circumference. */
  const fit = (cell: AtlasCell, axialShare: number, arcShare: number) =>
    Math.min(span * MAX_AXIAL * axialShare, cell.aspect * circumference * MAX_ARC * arcShare)

  const wordLength = fit(DECAL_ATLAS.wordmark, 1, 1)
  // The number is set larger than the wordmark on the real units.
  const numberLength = fit(numberCell, 0.62, 1.25)

  const gap = span * 0.05
  const total = wordLength + gap + numberLength

  // If the pair overruns the clear run, shrink both rather than clipping one.
  const k = total > span * 0.94 ? (span * 0.94) / total : 1

  const start = best[0] + (span - total * k) / 2
  const wordZ = start + (wordLength * k) / 2
  const numberZ = start + wordLength * k + gap * k + (numberLength * k) / 2

  const markings: Marking[] = []

  // Repeat the marking around the barrel so some of it faces the camera whatever
  // attitude the unit is in — eleven units in the hero lineup sit at eleven
  // different angles, and one wrapped label is legible across maybe 60°.
  //
  // HOW MANY depends on how much of the circumference one marking already takes,
  // which varies enormously across this range. On the SX 300 the wordmark spans 9°
  // of a 295 mm circumference, so four copies are still well separated. On the
  // SX 5/10 — a 19 mm bar — the same mark spans 61°, and four copies put print on
  // every face of what is effectively a square section: two of them showed at once
  // from any three-quarter view, one of them reversed, which reads as a printing
  // error rather than as a label. Opposite faces only, in that case.
  //
  // No copy needs its artwork flipped. That was necessary while the products were
  // swung end-over-end about world Y with their barrel across the frame, which
  // reverses the apparent axis direction along with the wrap; now they stand up
  // and rotate about the axis they actually have, so every copy comes round
  // reading the same way.
  const wordArc = (wordLength * k) / DECAL_ATLAS.wordmark.aspect / barrel.radius

  /**
   * A LYING product gets two copies, not four, and one of them is mirrored.
   *
   * theta is measured from the model's +Y. Laid down and turned about the vertical,
   * the copies at 0 and 180 are the ones on top of and underneath the barrel: they
   * stay on top and underneath for the whole revolution and are never square to the
   * camera, so they are not worth their triangles. The two that do present are at
   * 90 and 270, half a revolution apart — and because the barrel has swung end for
   * end between them, the one at 90 only reads the right way round with its artwork
   * mirrored.
   *
   * Two correct copies half a turn apart means a legible wordmark faces the reader
   * for most of every revolution, and a reversed one never does.
   */
  const lying = pose === 'lying'
  const copies = lying ? 2 : wordArc > Math.PI / 4 ? 2 : 4
  for (let q = 0; q < copies; q++) {
    const theta = lying ? Math.PI / 2 + q * Math.PI : (q * Math.PI * 2) / copies
    // sin(theta) > 0 is the model's +X side. That copy only presents itself after
    // the turntable has carried the unit through half a revolution, by which point
    // the barrel points the other way — so it is the one printed upside down.
    const flip = lying && Math.sin(theta) > 0
    markings.push({ cell: DECAL_ATLAS.wordmark, z: wordZ, length: wordLength * k, theta, flip })
    markings.push({ cell: numberCell, z: numberZ, length: numberLength * k, theta, flip })
  }

  // The discharge arrow, on the crown of the barrel so it never runs into the
  // label, as far toward the outlet as the clear run allows.
  const arrowLength = Math.min(span * 0.16, DECAL_ATLAS.arrow.aspect * circumference * 0.09)
  const arrowZ = best[1] - arrowLength * 0.75
  const labelEnd = numberZ + (numberLength * k) / 2
  if (arrowZ - arrowLength / 2 > labelEnd) {
    for (let q = 0; q < copies; q++) {
      const theta = lying
        ? Math.PI / 2 + q * Math.PI
        : Math.PI / copies + (q * Math.PI * 2) / copies
      // The arrow marks the discharge direction, so its orientation matters more
      // than type does: the same 180° turn that rights the wordmark is what keeps
      // the arrow pointing at the outlet rather than back down the barrel.
      const flip = lying && Math.sin(theta) > 0
      markings.push({ cell: DECAL_ATLAS.arrow, z: arrowZ, length: arrowLength, theta, flip })
    }
  }

  return markings
}

export function ProductDecals({ id }: { id: string }) {
  const pose = useContext(DecalPoseContext)

  // Configured in the load callback rather than by mutating the returned object:
  // R3F v9 no longer annotates texture props as sRGB automatically, so the colour
  // space has to be declared, and drei's own callback is the place to do it.
  const texture = useTexture('/textures/decals.png', (loaded) => {
    const t = Array.isArray(loaded) ? loaded[0] : loaded
    t.colorSpace = THREE.SRGBColorSpace
    t.anisotropy = 8
  })

  const geometry = useMemo(() => {
    const markings = layout(id, pose)
    const barrel = BARRELS[id]
    if (!markings || !barrel) return null

    const positions: number[] = []
    const normals: number[] = []
    const uvs: number[] = []
    for (const marking of markings) {
      pushPanel(positions, normals, uvs, barrel.radius, marking)
    }

    const g = new THREE.BufferGeometry()
    g.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
    g.setAttribute('normal', new THREE.Float32BufferAttribute(normals, 3))
    g.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2))
    return g
  }, [id, pose])

  const material = useMemo(() => {
    const barrel = BARRELS[id]
    if (!barrel) return null

    // The atlas is white art with an alpha channel; the tint is the material's,
    // which is what lets one texture serve white marks on the red bodies and dark
    // ones on the stainless.
    return new THREE.MeshStandardMaterial({
      map: texture,
      color: barrel.material === 'GF_Stainless' ? '#0D0F11' : '#F7F9FB',
      transparent: true,
      // The panel sits 0.6% of the radius off the surface. depthWrite off plus a
      // polygon offset keeps it from fighting the barrel at grazing angles or at
      // the far end of the hero dolly.
      depthWrite: false,
      polygonOffset: true,
      polygonOffsetFactor: -2,
      polygonOffsetUnits: -2,
      roughness: 0.55,
      metalness: 0,
      side: THREE.FrontSide,
      // Printed ink takes the environment far less than polished metal does.
      envMapIntensity: 0.15,
    })
  }, [id, texture])

  if (!geometry || !material) return null
  return <mesh geometry={geometry} material={material} renderOrder={1} />
}

useTexture.preload('/textures/decals.png')
