#!/usr/bin/env node
/**
 * gen:globe — bakes the About section's dotted globe into src/lib/globeMask.ts.
 *
 * The globe is a FIXED lattice of points spread evenly over a sphere (a Fibonacci
 * spiral, so no poles bunch up). Which of those points are land is the only thing
 * that needs shipping, and that is one bit per point: 16 000 points is 2 000 bytes,
 * where the land outlines they were tested against are 138 KB of GeoJSON. The
 * client rebuilds each point's position from its index with the same formula.
 *
 * Source: Natural Earth 1:110m land (public domain), assets/geo/ne_110m_land.geojson,
 * from https://github.com/nvkelso/natural-earth-vector. Re-run after changing
 * POINTS or the source file:  node scripts/gen-globe.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const SOURCE = join(ROOT, 'assets', 'geo', 'ne_110m_land.geojson')
const OUT = join(ROOT, 'src', 'lib', 'globeMask.ts')

/** Lattice size. Spacing is ~1.6° of arc — about 180 km at the equator. */
const POINTS = 16000

const land = JSON.parse(readFileSync(SOURCE, 'utf8'))

/** Every outer ring and hole, as [lon, lat] arrays, with a bbox for a fast reject. */
const polygons = []
for (const feature of land.features) {
  const g = feature.geometry
  const list = g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : []
  for (const rings of list) {
    let minX = Infinity
    let minY = Infinity
    let maxX = -Infinity
    let maxY = -Infinity
    for (const [x, y] of rings[0]) {
      minX = Math.min(minX, x)
      maxX = Math.max(maxX, x)
      minY = Math.min(minY, y)
      maxY = Math.max(maxY, y)
    }
    polygons.push({ rings, box: [minX, minY, maxX, maxY] })
  }
}

/** Even-odd ray cast. */
function inRing(lon, lat, ring) {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]
    const [xj, yj] = ring[j]
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside
  }
  return inside
}

function isLand(lon, lat) {
  for (const { rings, box } of polygons) {
    if (lon < box[0] || lon > box[2] || lat < box[1] || lat > box[3]) continue
    if (!inRing(lon, lat, rings[0])) continue
    let hole = false
    for (let h = 1; h < rings.length; h++) if (inRing(lon, lat, rings[h])) hole = true
    if (!hole) return true
  }
  return false
}

// The SAME lattice the client builds — see fibonacciPoint in src/lib/network.ts.
const GOLDEN = Math.PI * (3 - Math.sqrt(5))
const bits = new Uint8Array(Math.ceil(POINTS / 8))
let count = 0
for (let i = 0; i < POINTS; i++) {
  const y = 1 - ((i + 0.5) / POINTS) * 2
  const r = Math.sqrt(1 - y * y)
  const theta = i * GOLDEN
  const x = Math.cos(theta) * r
  const z = Math.sin(theta) * r
  const lat = (Math.asin(y) * 180) / Math.PI
  const lon = (Math.atan2(x, z) * 180) / Math.PI
  if (isLand(lon, lat)) {
    bits[i >> 3] |= 1 << (i & 7)
    count++
  }
}

const b64 = Buffer.from(bits).toString('base64')
writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-globe.mjs — do not edit by hand.
//
// One bit per point of a ${POINTS}-point Fibonacci lattice: set where the point is
// land in Natural Earth 1:110m (public domain). ${count} land points.

export const GLOBE_POINTS = ${POINTS}

export const LAND_MASK_B64 =
  '${b64}'
`,
)
console.log(`gen:globe — ${count} of ${POINTS} lattice points are land → src/lib/globeMask.ts (${bits.length} bytes)`)
